### PR TITLE
Initial support for the Philomena API

### PR DESCRIPTION
**Pull request by jozsefsallai**
Derpibooru was rewritten from the ground up a few months ago and while some of the old API endpoints are still available, they will soon become deprecated and unavailable. See this forum post: https://derpibooru.org/forums/meta/topics/old-api-deprecation-notice

The docs for the new Philomena API are available here: https://derpibooru.org/pages/api

This pull request changes the way the Link class works, so that it will fetch `/api/v1/json/:endpoint` instead of `/:endpoint.json`. It also changes the link for the Search class from "search" to "search/images" (Derpi's search API has a lot of other endpoints to work with now, you might want to implement them as separate methods, if you want). For the most important part, everything works, however there are a few things that do not currently work (and aren't really the module's fault):

 - There are no endpoints for Lists anymore. Maybe they've recently removed them completely?
 - The Search API no longer accepts `random_image` as a query parameter, thus the `.random()` method will always return undefined.

### CODE REVIEW

**Comment by octet-stream** [comment]
Hi! I'm planning to add a support of the new API until March 31st, so don't worry about that.
I just need to find some time to dive into new API and implements support for the new endpoints :)

> There are no endpoints for Lists anymore. Maybe they've recently removed them completely?

Yes, everything that doesn't supported by API will be completely removed from dinky as well.

**Comment by jozsefsallai** [comment]
> I'm planning to add a support of the new API until March 31st, so don't worry about that.
> I just need to find some time to dive into new API and implements support for the new endpoints :)

No worries, take your time :) this PR was meant to be more of a starting point for you! Luckily, you designed the library in a very nice way, so it is super easy to implement the changes!

> Yes, everything that doesn't supported by API will be completely removed from dinky as well.

I just wonder why they decided to remove `random_image`, I use that feature in my Discord bot (thanks for the star btw 💚). Maybe they plan on making it a separate endpoint? That would be really neat since it would require just one query instead of two.

Glad to see you still have interest in this library! I love it, keep it up :) 

also, Luna is best princess

**Comment by jozsefsallai** [comment]
Update on the random() situation: https://derpibooru.org/forums/meta/topics/old-api-deprecation-notice?post_id=4707333#post_4707333

Seems like this is a very good option, since it returns the image directly: https://derpibooru.org/api/v1/json/search/images?q=princess+luna&sf=random&per_page=1
No need for double requests 🎉

**Comment by octet-stream** [comment]
> No worries, take your time :) this PR was meant to be more of a starting point for you! Luckily, you designed the library in a very nice way, so it is super easy to implement the changes!

It seems like a lot changed in the new API, search now has resolve tags, comments and so on. And that's where I'm struggle. Perhaps I need to do some changes for Search class. Or maybe across the whole Dinky's architecture.

Yeah, seems like they haven't documented what happened to random_image parameter, but I saw that one in browser's omnibox when searched around for ponies.

I actually had started to work on the next version, but I can merge this PR anyway, or keep it open until I will resolve the issue. Thanks again.

**Comment by octet-stream** [comment]
> also, Luna is best princess

<details>
  <summary>Agree :></summary>

  1381085__safe_artist-colon-meow_princess+luna_alicorn_bed_bedtime+story_book_cute_filly_lunabetes_on+back_pillow_pony_solo_woona_younger
</details>

**Comment by octet-stream** [comment]
I have changed the target branch, that's where I'm working on a new version.

**Review by octet-stream — APPROVED** [review]

**Comment by octet-stream** [comment]
Okay, I think it's time to cut a new release. I only need to rewrite documentation to match the current project's state and everything is ready to go.
Also, I decided to keep `Lists` class, but it will be just a bunch of shortcuts for Search. You'll see from the docs.

**Comment by jozsefsallai** [comment]
<details>
<summary>yay! :)</summary>

image

</details>

**Comment by octet-stream** [comment]
You can now get the v1.0 with the new API support.

Don't forget:
1. The `Search#random()` now returns `Search` instance instead of a random image.
2. If you want to keep the previous behaviour for this method, you also have to call `Search#limit()` to set the search limit.

So, that's how you'll match the previous behavour:

```js
import dinky from "dinky.js"

dinky().search(["princess luna", "safe"]).random().limit(1)
  .then(({images}) => images[0])
```

**Comment by jozsefsallai** [comment]
<details>
<summary>Thank you so much for your hard work! :D</summary>

image

</summary>

**Comment by octet-stream** [comment]
@Veetaha, @PinkiePieIsTheBestPony just a reminder: Don't forget to upgrade Dinky to v1.0

**Comment by Veetaha** [comment]
Thanks, nice to see that things are developing!

**Comment by PinkiePieIsTheBestPony** [comment]
Thank you for the reminder!

**Pull request merged**
